### ISSUE TITLE
Add entry for Broad PGM API

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/translator-api-registry#3]

**Comment by cmungall** [comment]
cc @vblank

**Comment by newgene** [comment]
@vdancik thanks for submitting the PGM API to the registry!

There are a few issues to be fixed in order to have it pass the validation:

* Fix the mis-match in the entry from API_LIST.yml and the actual file name (openapi.yaml v.s. openapi.yml)
* Add a required "translator" tag. See the example [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_minimum.yml#L19).
* Add a required github link for the responsible dev. See the example [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_minimum.yml#L15).

Other than that, it looks good to me.

**Comment by vdancik** [comment]
@newgene thanks for the comments, they were addressed in the updated version.

**Comment by newgene** [comment]
@vdancik thanks. PGM API is now on SmartAPI registry! http://smart-api.info/registry 

Though optional, it will be nice to provide an "info.description" field (supports MarkDown) for your API, like other APIs, e.g. pointing to the website. It also renders better in the registry.
